from . import res_partner
from . import motivo
from . import issue
from . import estudio_titulo
from . import estudio
from . import idioma
from . import profesion
from . import familiar
from . import empleo
from . import obra_social
from . import caja_jubilatoria
from . import universidad
